apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: ddiiwoong/hello-python:latest
            env:
            - name: TARGET
              value: "Python Sample v1 with Knative on EKS"