apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          serviceAccountName: knative-serve
          container:
            image: 208357897717.dkr.ecr.ap-northeast-2.amazonaws.com/hello-python
            env:
            - name: TARGET
              value: "Python Sample v1"